# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the app in debug configuration"
  lane :build_app_debug do
    build_ios_app(
      project: "BDZDelays.xcodeproj",
      scheme: "BDZDelays",
      configuration: "Debug",
      clean: true,
      export_method: "development",
      skip_codesigning: true,
      skip_archive: true,
      sdk: "iphoneos16.2"
    )
  end

  desc "Run all tests"
  lane :tests do
    for scheme in [
      "StationDomain", 
      "SearchStationDomain",
      "ROVR",
    ] do
      run_tests(
        package_path: "BDZDelays/bdz-delays",
        scheme: scheme,
        device: "iPhone 13 Pro Max",
        result_bundle: true,
        output_directory: Dir.pwd + "/test_output"  # https://github.com/fastlane/fastlane/issues/20012
      )
    end
  end
end
