# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build the iOS app in debug configuration for iOS 16.4"
  lane :build_app_debug do
    build_ios_app(
      project: "BDZDelays.xcodeproj",
      scheme: "BDZDelays",
      configuration: "Debug",
      clean: true,
      export_method: "development",
      skip_codesigning: true,
      skip_archive: true,
      sdk: "iphoneos16.4"
    )
  end

  desc "Run all tests"
  lane :tests do
    run_tests(
      scheme: "BDZDelays",
      device: "iPhone 13 Pro Max",
      result_bundle: true,
      skip_build: true
    )
  end
end

platform :mac do
  desc "Build the macOS app in debug configuration for macOS 13"
  lane :build_app_debug do
    build_mac_app(
      project: "BDZDelays.xcodeproj",
      scheme: "BDZDelays",
      configuration: "Debug",
      clean: true,
      export_method: "development",
      skip_codesigning: true,
      skip_archive: true,
    )
  end
end