import Foundation

public enum ROVRStation: Int {
    case avramovo = 141
    case aytos = 817
    case aldomirovci = 8
    case alfatar = 925
    case anton = 434
    case asenovgrad = 166
    case asparuhovo = 501
    case bankya = 109
    case bansko = 152
    case banya = 857
    case batanovci = 638
    case bezmer = 809
    case beliIzvor = 734
    case belica = 147
    case belovo = 45
    case belozem = 788
    case beloslav = 285
    case berkovica = 774
    case blagoevgrad = 661
    case boboshevo = 657
    case bov = 182
    case boychinovci = 740
    case borovo = 531
    case botev = 446
    case botunec = 416
    case bracigovo = 162
    case brigadir = 697
    case brusarci = 745
    case bunovo = 427
    case burgas = 830
    case bulgarovo = 820
    case byala = 534
    case vakarel = 31
    case varvara = 126
    case varna = 293
    case varnaFerry = 405
    case velikoTarnovo = 550
    case velingrad = 134
    case velichkovo = 504
    case verinsko = 32
    case vetovo = 894
    case vidinPassenger = 762
    case vidinCargo = 761
    case visokaPolyana = 902
    case vlTrichkov = 174
    case vladaya = 628
    case ВvladimirPavlov = 829
    case voluyak = 14
    case vraca = 732
    case valchiDol = 387
    case gabrovo = 625
    case gavrailovo = 474
    case genTodorov = 676
    case genToshev = 397
    case bigVillage = 681
    case gorPriemPark = 547
    case gornaBanya = 627
    case gornaBanyaSp = 633
    case gornaOryahovitsa = 238
    case gorniDabnik = 214
    case grafIgnatievo = 848
    case gurkovo = 466
    case gyueshevo = 728
    case damyanica = 675
    case daskalovo = 630
    case dveMogili = 529
    case debelec = 552
    case devnya = 381
    case delyan = 648
    case dzhulyunica = 241
    case dimitrovgrad = 77
    case dimitrovgradSv = 579
    case dimovo = 754
    case dobrinishte = 154
    case dobrich = 392
    case doyranci = 352
    case dolapite = 524
    case dyulene = 131
    case dolnaMahala = 851
    case dolnaMitropoliya = 328
    case dolniDabnik = 215
    case dolniRakovec = 643
    case dolnoEzer = 825
    case dolnoKamarci = 426
    case dragichevo = 629
    case dragoman = 6
    case dralfa = 253
    case drenovec = 747
    case druzhba = 822
    case dryanovo = 556
    case dulovo = 922
    case dunavci = 458
    case dupnica = 653
    case dabovo = 463
    case dalgopol = 503
    case daskotna = 496
    case dyakovo = 650
    case ezerovo = 288
    case elinPelin = 27
    case eliseyna = 189
    case zhelyuVoyvoda = 478
    case zavet = 492
    case zavoy = 811
    case zaharnaFabrika = 626
    case zverino = 191
    case zemen = 711
    case zimnica = 479
    case zlatica = 431
    case zmeyovo = 571
    case ivanovo = 526
    case iliyanci = 170
    case iskar = 23
    case iskarskoShose = 946
    case isperih = 916
    case ithiman = 35
    case kazanlak = 460
    case kazichene = 25
    case kalitinovo = 800
    case kalotina = 3
    case kalotinaZapad = 2
    case kalofer = 449
    case kaloyanovec = 796
    case kaloyanovo = 849
    case kapiKule = 92
    case karadzhalovo = 72
    case kardam = 398
    case karlovo = 444
    case karlukovo = 207
    case karnobat = 483
    case kaspichan = 270
    case katunica = 66
    case kermen = 807
    case klisura = 437
    case kozarevec = 240
    case komunari = 377
    case horsovo = 806
    case koprivshtica = 435
    case kostandovo = 133
    case kostenec = 41
    case kostinbrod = 12
    case kocherinovo = 659
    case krakra = 636
    case kremikovci = 415
    case kresna = 670
    case krivodol = 736
    case krichim = 159
    case krumovo = 64
    case krastec = 565
    case kulata = 679
    case kunino = 206
    case kurilo = 172
    case kardzhali = 599
    case kyustendil = 718
    case lakatnik = 184
    case levski = 225
    case lovech = 357
    case lovechSeverRp = 355
    case lozarevo = 486
    case lom = 780
    case lyubenovoPred = 868
    case lyubimec = 87
    case lyulyakovoRp = 494
    case makocevo = 424
    case manole = 787
    case medkovec = 744
    case mezdra = 198
    case mezdraYug = 196
    case mericleri = 577
    case metalStop = 631
    case mirkovo = 428
    case mihaylovo = 573
    case mominProhod = 40
    case momchilGrad = 602
    case montana = 768
    case morunica = 532
    case most = 589
    case musachevoRp = 512
    case murchevo = 741
    case mutnica = 267
    case novaZagora = 805
    case novaNadezhda = 81
    case obedinena = 514
    case obrazvocChiflik = 891
    case ognyanovo = 53
    case oresh = 341
    case oreshec = 751
    case orizovo = 790
    case pavelBanya = 455
    case pavlikeni = 229
    case pazardzhik = 51
    case panagyurishte = 846
    case peyoYavorov = 668
    case pernik = 635
    case pernikRazpred = 632
    case petkoKaravelov = 539
    case petrich = 688
    case peturch = 11
    case peshtera = 163
    case pirdop = 433
    case plachkovci = 562
    case pleven = 219
    case plevenZapad = 218
    case pliska = 908
    case plovdiv = 60
    case plovdivRazpred = 164
    case pobitKamak = 28
    case povelyanovo = 283
    case podvis = 489
    case podkova = 606
    case poduyanePatn = 20
    case polikraishte = 235
    case polskiTrambesh = 536
    case popovica = 69
    case popovo = 248
    case pordim = 222
    case prileprp = 490
    case provadiya = 275
    case prostorno = 897
    case parvomay = 71
    case radnevo = 871
    case radomir = 641
    case radunci = 567
    case razdhavica = 714
    case razgrad = 899
    case razdelna = 282
    case razlog = 151
    case razmenna = 689
    case rebrovo = 176
    case resen = 233
    case roman = 204
    case ruse = 522
    case ruseZapad = 887
    case ruseRazpred = 520
    case ruseSever = 909
    case ruskaByala = 730
    case sadovo = 67
    case samovodene = 548
    case samuil = 901
    case sandanski = 674
    case saranci = 422
    case sahrene = 456
    case svetovrachene = 412
    case svilengrad = 88
    case svishtov = 338
    case svoboda = 794
    case svoge = 179
    case senovo = 896
    case septemvri = 47
    case silistra = 928
    case simeonovgrad = 83
    case simitli = 664
    case sindel = 280
    case skutare = 786
    case slavyanovo = 246
    case sliven = 476
    case slivnica = 10
    case smyadovo = 372
    case somovit = 336
    case sopot = 443
    case sofia = 18
    case sofiaSever = 169
    case sracimir = 756
    case stamboliyski = 56
    case stanyanci = 100
    case staraZagora = 572
    case stolnik = 419
    case strazhica = 243
    case straldzha = 480
    case strelcha = 845
    case strumyani = 672
    case stryama = 436
    case suvorovo = 385
    case saedinenie = 838
    case tvardica = 468
    case telish = 213
    case todorKableshkov = 58
    case topolite = 290
    case trakia = 831
    case troyan = 368
    case trud = 847
    case tryavna = 560
    case tulovo = 462
    case tazha = 452
    case targovishte = 257
    case tarnak = 499
    case filipovo = 784
    case hanAsparuh = 803
    case hanKrum = 262
    case harmanli = 85
    case haskovo = 583
    case hisar = 860
    case hitrino = 904
    case hrabarsko = 699
    case hristoDanovo = 439
    case carLivada = 558
    case cvetino = 138
    case cerkovski = 482
    case chervenBryag = 209
    case cherganovo = 461
    case cherkvica = 337
    case chernaGora = 791
    case cherniche = 665
    case chernograd = 814
    case chirpan = 793
    case chukurovo = 123
    case shivachevo = 470
    case shumen = 265
    case yunak = 507
    case yabalkovo = 75
    case yakoruda = 144
    case yambol = 810
    case yana = 417
    case yantra = 542
    case yasen = 216
}

public extension ROVRStation {
    init?(_ string: String) {
        switch string {
        case "Аврамово": self = .avramovo
        case "Айтос": self = .aytos
        case "Алдомировци": self = .aldomirovci
        case "Алфатар": self = .alfatar
        case "Антон": self = .anton
        case "Асеновград": self = .asenovgrad
        case "Аспарухово": self = .asparuhovo
        case "Банкя": self = .bankya
        case "Банско": self = .bansko
        case "Баня": self = .banya
        case "Батановци": self = .batanovci
        case "Безмер": self = .bezmer
        case "Бели извор": self = .beliIzvor
        case "Белица": self = .belica
        case "Белово": self = .belovo
        case "Белозем": self = .belozem
        case "Белослав": self = .beloslav
        case "Берковица": self = .berkovica
        case "Благоевград": self = .blagoevgrad
        case "Бобошево": self = .boboshevo
        case "Бов": self = .bov
        case "Бойчиновци": self = .boychinovci
        case "Борово": self = .borovo
        case "Ботев": self = .botev
        case "Ботунец": self = .botunec
        case "Брацигово": self = .bracigovo
        case "Бригадир": self = .brigadir
        case "Брусарци": self = .brusarci
        case "Буново": self = .bunovo
        case "Бургас": self = .burgas
        case "Българово": self = .bulgarovo
        case "Бяла": self = .byala
        case "Вакарел": self = .vakarel
        case "Варвара": self = .varvara
        case "Варна": self = .varna
        case "Варна ферибоот.": self = .varnaFerry
        case "Велико търново": self = .velikoTarnovo
        case "Велинград": self = .velingrad
        case "Величково": self = .velichkovo
        case "Веринско": self = .verinsko
        case "Ветово": self = .vetovo
        case "Видин пътн.": self = .vidinPassenger
        case "Видин товарна": self = .vidinCargo
        case "Висока поляна": self = .visokaPolyana
        case "Вл.тричков": self = .vlTrichkov
        case "Владая": self = .vladaya
        case "Владимир павлов": self = .ВvladimirPavlov
        case "Волуяк": self = .voluyak
        case "Враца": self = .vraca
        case "Вълчи дол": self = .valchiDol
        case "Габрово": self = .gabrovo
        case "Гавраилово": self = .gavrailovo
        case "Ген.тодоров": self = .genTodorov
        case "Ген.тошев": self = .genToshev
        case "Голямо село": self = .bigVillage
        case "Гор прием.парк": self = .gorPriemPark
        case "Горна баня": self = .gornaBanya
        case "Горна баня сп": self = .gornaBanyaSp
        case "Горна оряховица": self = .gornaOryahovitsa
        case "Горни дъбник": self = .gorniDabnik
        case "Граф игнатиево": self = .grafIgnatievo
        case "Гурково": self = .gurkovo
        case "Гюешево": self = .gyueshevo
        case "Дамяница": self = .damyanica
        case "Даскалово": self = .daskalovo
        case "Две могили": self = .dveMogili
        case "Дебелец": self = .debelec
        case "Девня": self = .devnya
        case "Делян": self = .delyan
        case "Джулюница": self = .dzhulyunica
        case "Димитровград": self = .dimitrovgrad
        case "Димитровград св": self = .dimitrovgradSv
        case "Димово": self = .dimovo
        case "Добринище": self = .dobrinishte
        case "Добрич": self = .dobrich
        case "Дойренци": self = .doyranci
        case "Долапите": self = .dolapite
        case "Долене": self = .dyulene
        case "Долна махала": self = .dolnaMahala
        case "Долна митропол.": self = .dolnaMitropoliya
        case "Долни дъбник": self = .dolniDabnik
        case "Долни раковец": self = .dolniRakovec
        case "Долно езер.": self = .dolnoEzer
        case "Долно камарци": self = .dolnoKamarci
        case "Драгичево": self = .dragichevo
        case "Драгоман": self = .dragoman
        case "Дралфа": self = .dralfa
        case "Дреновец": self = .drenovec
        case "Дружба": self = .druzhba
        case "Дряново": self = .dryanovo
        case "Дулово": self = .dulovo
        case "Дунавци": self = .dunavci
        case "Дупница": self = .dupnica
        case "Дъбово": self = .dabovo
        case "Дългопол": self = .dalgopol
        case "Дъскотна": self = .daskotna
        case "Дяково": self = .dyakovo
        case "Езерово": self = .ezerovo
        case "Елин пелин": self = .elinPelin
        case "Елисейна": self = .eliseyna
        case "Желю войвода": self = .zhelyuVoyvoda
        case "Завет": self = .zavet
        case "Завой": self = .zavoy
        case "Захарна фабрика": self = .zaharnaFabrika
        case "Зверино": self = .zverino
        case "Земен": self = .zemen
        case "Зимница": self = .zimnica
        case "Златица": self = .zlatica
        case "Змейово": self = .zmeyovo
        case "Иваново": self = .ivanovo
        case "Илиянци": self = .iliyanci
        case "Искър": self = .iskar
        case "Искърско шосе": self = .iskarskoShose
        case "Исперих": self = .isperih
        case "Ихтиман": self = .ithiman
        case "Казанлък": self = .kazanlak
        case "Казичене": self = .kazichene
        case "Калитиново": self = .kalitinovo
        case "Калотина": self = .kalotina
        case "Калотина запад": self = .kalotinaZapad
        case "Калофер": self = .kalofer
        case "Калояновец": self = .kaloyanovec
        case "Калояново": self = .kaloyanovo
        case "Капъ куле": self = .kapiKule
        case "Караджалово": self = .karadzhalovo
        case "Кардам": self = .kardam
        case "Карлово": self = .karlovo
        case "Карлуково": self = .karlukovo
        case "Карнобат": self = .karnobat
        case "Каспичан": self = .kaspichan
        case "Катуница": self = .katunica
        case "Кермен": self = .kermen
        case "Клисура": self = .klisura
        case "Козаревец": self = .kozarevec
        case "Комунари": self = .komunari
        case "Коньово": self = .horsovo
        case "Копривщица": self = .koprivshtica
        case "Костандово": self = .kostandovo
        case "Костенец": self = .kostenec
        case "Костинброд": self = .kostinbrod
        case "Кочериново": self = .kocherinovo
        case "Кракра": self = .krakra
        case "Кремиковци": self = .kremikovci
        case "Кресна": self = .kresna
        case "Криводол": self = .krivodol
        case "Кричим": self = .krichim
        case "Крумово": self = .krumovo
        case "Кръстец": self = .krastec
        case "Кулата": self = .kulata
        case "Кунино": self = .kunino
        case "Курило": self = .kurilo
        case "Кърджали": self = .kardzhali
        case "Кюстендил": self = .kyustendil
        case "Лакатник": self = .lakatnik
        case "Левски": self = .levski
        case "Ловеч": self = .lovech
        case "Ловеч север рп": self = .lovechSeverRp
        case "Лозарево": self = .lozarevo
        case "Лом": self = .lom
        case "Любеново пред.": self = .lyubenovoPred
        case "Любимец": self = .lyubimec
        case "Люляково рп": self = .lyulyakovoRp
        case "Макоцево": self = .makocevo
        case "Маноле": self = .manole
        case "Медковец": self = .medkovec
        case "Мездра": self = .mezdra
        case "Мездра юг": self = .mezdraYug
        case "Меричлери": self = .mericleri
        case "Метал спирка": self = .metalStop
        case "Мирково": self = .mirkovo
        case "Михайлово": self = .mihaylovo
        case "Момин проход": self = .mominProhod
        case "Момчилград": self = .momchilGrad
        case "Монтана": self = .montana
        case "Моруница": self = .morunica
        case "Мост": self = .most
        case "Мусачево рп": self = .musachevoRp
        case "Мърчево": self = .murchevo
        case "Мътница": self = .mutnica
        case "Нова загора": self = .novaZagora
        case "Нова надежда": self = .novaNadezhda
        case "Обединена": self = .obedinena
        case "Образцов чифлик": self = .obrazvocChiflik
        case "Огняново": self = .ognyanovo
        case "Ореш": self = .oresh
        case "Орешец": self = .oreshec
        case "Оризово": self = .orizovo
        case "Павел баня": self = .pavelBanya
        case "Павликени": self = .pavlikeni
        case "Пазарджик": self = .pazardzhik
        case "Панагюрище": self = .panagyurishte
        case "Пейо яворов": self = .peyoYavorov
        case "Перник": self = .pernik
        case "Перник разпред.": self = .pernikRazpred
        case "Петко каравелов": self = .petkoKaravelov
        case "Петрич": self = .petrich
        case "Петърч": self = .peturch
        case "Пещера": self = .peshtera
        case "Пирдоп": self = .pirdop
        case "Плачковци": self = .plachkovci
        case "Плевен": self = .pleven
        case "Плевен запад": self = .plevenZapad
        case "Плиска": self = .pliska
        case "Пловдив": self = .plovdiv
        case "Пловдив разпр.": self = .plovdivRazpred
        case "Побит камък": self = .pobitKamak
        case "Повеляново": self = .povelyanovo
        case "Подвис": self = .podvis
        case "Подкова": self = .podkova
        case "Подуяне пътн.": self = .poduyanePatn
        case "Поликраище": self = .polikraishte
        case "Полски тръмбеш": self = .polskiTrambesh
        case "Поповица": self = .popovica
        case "Попово": self = .popovo
        case "Пордим": self = .pordim
        case "Прилеп рп": self = .prileprp
        case "Провадия": self = .provadiya
        case "Просторно": self = .prostorno
        case "Първомай": self = .parvomay
        case "Раднево": self = .radnevo
        case "Радомир": self = .radomir
        case "Радунци": self = .radunci
        case "Раждавица": self = .razdhavica
        case "Разград": self = .razgrad
        case "Разделна": self = .razdelna
        case "Разлог": self = .razlog
        case "Разменна": self = .razmenna
        case "Реброво": self = .rebrovo
        case "Ресен": self = .resen
        case "Роман": self = .roman
        case "Русе": self = .ruse
        case "Русе запад": self = .ruseZapad
        case "Русе разпредел.": self = .ruseRazpred
        case "Русе север": self = .ruseSever
        case "Руска бяла": self = .ruskaByala
        case "Садово": self = .sadovo
        case "Самоводене": self = .samovodene
        case "Самуил": self = .samuil
        case "Сандански": self = .sandanski
        case "Саранци": self = .saranci
        case "Сахране": self = .sahrene
        case "Световрачене": self = .svetovrachene
        case "Свиленград": self = .svilengrad
        case "Свищов": self = .svishtov
        case "Свобода": self = .svoboda
        case "Своге": self = .svoge
        case "Сеново": self = .senovo
        case "Септември": self = .septemvri
        case "Силистра": self = .silistra
        case "Симеоновград": self = .simeonovgrad
        case "Симитли": self = .simitli
        case "Синдел": self = .sindel
        case "Скутаре": self = .skutare
        case "Славяново": self = .slavyanovo
        case "Сливен": self = .sliven
        case "Сливница": self = .slivnica
        case "Смядово": self = .smyadovo
        case "Сомовит": self = .somovit
        case "Сопот": self = .sopot
        case "София": self = .sofia
        case "София север": self = .sofiaSever
        case "Срацимир": self = .sracimir
        case "Стамболийски": self = .stamboliyski
        case "Станянци": self = .stanyanci
        case "Стара загора": self = .staraZagora
        case "Столник": self = .stolnik
        case "Стражица": self = .strazhica
        case "Стралджа": self = .straldzha
        case "Стрелча": self = .strelcha
        case "Струмяни": self = .strumyani
        case "Стряма": self = .stryama
        case "Суворово": self = .suvorovo
        case "Съединение": self = .saedinenie
        case "Твърдица": self = .tvardica
        case "Телиш": self = .telish
        case "Тодор каблешков": self = .todorKableshkov
        case "Тополите": self = .topolite
        case "Тракия": self = .trakia
        case "Троян": self = .troyan
        case "Труд": self = .trud
        case "Трявна": self = .tryavna
        case "Тулово": self = .tulovo
        case "Тъжа": self = .tazha
        case "Търговище": self = .targovishte
        case "Търнак": self = .tarnak
        case "Филипово": self = .filipovo
        case "Хан аспарух": self = .hanAsparuh
        case "Хан крум": self = .hanKrum
        case "Харманли": self = .harmanli
        case "Хасково": self = .haskovo
        case "Хисар": self = .hisar
        case "Хитрино": self = .hitrino
        case "Храбърско": self = .hrabarsko
        case "Христо даново": self = .hristoDanovo
        case "Цар.ливада": self = .carLivada
        case "Цветино": self = .cvetino
        case "Церковски": self = .cerkovski
        case "Червен бряг": self = .chervenBryag
        case "Черганово": self = .cherganovo
        case "Черквица": self = .cherkvica
        case "Черна гора": self = .chernaGora
        case "Черниче": self = .cherniche
        case "Черноград": self = .chernograd
        case "Чирпан": self = .chirpan
        case "Чукурово": self = .chukurovo
        case "Шивачево": self = .shivachevo
        case "Шумен": self = .shumen
        case "Юнак": self = .yunak
        case "Ябълково": self = .yabalkovo
        case "Якоруда": self = .yakoruda
        case "Ямбол": self = .yambol
        case "Яна": self = .yana
        case "Янтра": self = .yantra
        case "Ясен": self = .yasen
            
        default: return nil
        }
    }
}
