name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  ios-debug-build:
    name: Build iOS app in Debug config
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install fastlane
        run: |
          brew install fastlane

      - name: Switch to Xcode 14.3
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app
          
      - name: Build iOS app (debug config)
        run: |
          fastlane ios build_app_debug

  mac-debug-build:
    name: Build macOS app in Debug config
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install fastlane
        run: |
          brew install fastlane

      - name: Switch to Xcode 14.3
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app
          
      - name: Build macOS app (debug config)
        run: |
          fastlane mac build_app_debug

  tests:
    name: Run all tests
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install fastlane
        run: |
          brew install fastlane

      - name: Switch to Xcode 14.3
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app
          
      - name: Run tests
        run: |
          fastlane tests
      
