name: Build

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches: [ "main" ]

jobs:
  debug-build:
    name: Build the main scheme in Debug configuration
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Fastlane
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: build_app_debug
