name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  debug-build:
    name: Build the main scheme in Debug configuration
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install fastlane
        run: |
          brew install fastlane
          
      - name: Run lane
        run: |
          fastlane build_app_debug
      
