name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  debug-build:
    name: Build app in Debug config
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install fastlane
        run: |
          brew install fastlane
          
      - name: Build iOS app (debug config)
        run: |
          fastlane build_app_debug

  tests:
    name: Run all tests
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install fastlane
        run: |
          brew install fastlane
          
      - name: Run tests
        run: |
          fastlane tests
      
