name: Upload iOS app to Testflight
on: workflow_dispatch

jobs:
  release_build:
    runs-on: macos13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install certificate and provisioning profiles
        env:
          APPLE_DISTRIBUTION_CERT_B64: ${{ secrets.APPLE_DISTRIBUTION_CERT_B64 }}
          APPLE_DISTRIBUTION_CERT_PASSWD: ${{ secrets.APPLE_DISTRIBUTION_CERT_PASSWD }}
          IOS_DISTRIBUTION_PROV_PROFILE_B64: ${{ secrets.IOS_DISTRIBUTION_PROV_PROFILE_B64 }}
          KEYCHAIN_PASSWD: ${{ secrets.KEYCHAIN_PASSWD }}
        run: |
          CERT_PATH=$RUNNER_TEMP/build_cert.p12
          IOS_PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$APPLE_DISTRIBUTION_CERT_B64" | base64 --decode -o $CERT_PATH
          echo -n "$IOS_DISTRIBUTION_PROV_PROFILE_B64" | base64 --decode -o $IOS_PP_PATH

          security create-keychain -p "$KEYCHAIN_PASSWD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWD" $KEYCHAIN_PATH

          security import $CERT_PATH -P "$APPLE_DISTRIBUTION_CERT_PASSWD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $IOS_PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install fastlane
        run: |
          brew install fastlane

      - name: Switch to Xcode 14.3
        run: |
          sudo xcode-select -s /Applications/Xcode_14.3.app

      - name: Decode GoogleService-Info.plist
        run: |
          echo ${{ secrets.GOOGLE_PLIST_CONTENT_B64 }} | base64 --decode > "${GITHUB_WORKSPACE}/BDZDelays/GoogleService-Info.plist"
    
      - name: Deploy to Testflight
        run: |
          fastlane testflight